tdd/lists/urls.py
from django.conf.urls import url
from django.contrib import admin

from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

tdd/tdd/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls))
]

tdd/lists/models.py
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default=None)
    list = models.ForeignKey(List, default=None)

tdd/lists/forms.py
from django import forms

from lists.models import Item

EMPTY_ERROR_ITEM = "You can't have an empty list item"


class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ERROR_ITEM}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

tdd/lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError

from lists.forms import ItemForm
from lists.models import Item, List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)

    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {'form': form})

tdd/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-US-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do lists</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>
    <body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>
                    <form method="post" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block">{{ form.text.errors }}</span>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>
    </div>
    </body>
</html>

tdd/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

tdd/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}